services:
  - type: web
    name: mlops-fraud-detector
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: LOG_LEVEL
        value: INFO
